#!/bin/bash

CURR_PHP_VER=`php -v | grep 'PHP.*cli' | sed -E 's/.*([0-9])+\.([0-9]+)\.[0-9]+.*/php\1\2/'`
TARGET_PHP_VER=`echo "php${1}"`

echo

if [ $CURR_PHP_VER == $TARGET_PHP_VER ]; then
    echo "Nothing to do."
    exit 1
fi

echo "Switch version from ${CURR_PHP_VER} to ${TARGET_PHP_VER} ..."
echo

CURR_EXTS=`php -m 2>&1`

brew unlink $CURR_PHP_VER

brew link $TARGET_PHP_VER

TARGET_EXTS=`php -m 2>&1`

echo
echo "Done!"
echo

echo "Extension differences:"

diff -u <(echo "$CURR_EXTS") <(echo "$TARGET_EXTS") 2>&- | php -r '
    echo implode(preg_filter(
        "/^(\+|-)([a-z0-9_ ]+)$/i",
        "$1 $2",
        explode("\n", file_get_contents("php://stdin"))
    ), PHP_EOL);
'
